### ISSUE TITLE
nom

### ISSUE THREAD

**Issue by tatasss** [programgames/ixionlegrandmonarque#1]
Salut,
Je comprend pas le nom, tu peux me dire à quoi sert ce projet ?
Cordialement

**Comment by programgames** [comment]
Ce projet correspond à un site web qui a pour but recenser divers informations au sujet de jeux vidéos tel que Minecraft , League of Legends, notamment d'utiliser des api qui leur correspondent tout cela en utilisant le framework symfony dans un but d'apprentissage.
